apiVersion: v1
kind: Secret
metadata:
  name: common-bb
stringData:
  # TLS key pair for *.bigbang.dev is used as an example for demo purposes
  values.yaml: |-
    istio:
      gateways:
        public:
          tls:
            key: |-
              -----BEGIN PRIVATE KEY-----
              MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDCPEGQXIMlxmGS
              T+ZYgxTv6hHBeNOciXj1glmvSsKxqhTjYmfoi52bTW59szBg8XCUFCulkesIdkFz
              EWaUKMNFinLUIJVlkXMNRbut8deNUzKzGfOO8zj8BUTUg9tecARbyCoKJIHqDhpQ
              4PsKov5Pm9KnVe0Mxh0X7RUR9RZCKSa+vCfK6BCvvu41ghIwTlskufiWLI/uptFK
              5ZQX6h/lb2emhVU5OSrD5wAJd0Qme/Xj8auSLYxKyDnowiihn4z0CtkTTPdd+LdY
              fkQihX/xGUFuSdBx07tgzKWpoKYXe2GhxDFk2dfGM0iXrIyCWJc+mSimK5afdIeC
              +iUWlF4dAgMBAAECggEBAKm6ZcB0VtXHiLOFxk9KHB2ZeHKL1r5PErfWc/BNb9w4
              N5CLCSmX9t0iyI5m6ruLv0hmZ82CuNLoI0Edz3lgNWKrHLRo1KOwecz7Rok1b5o7
              PW5sGvyrZPw0znS11Bet4uEhBDtgs3WHZU+PiU8+JuQB0g4Pc9lZtUqXDXZnqE+e
              hpcSVPekJKzphqvwNNgPaqNsvfd7jP3ckQ1sTT48gBN8C7PItL23LHKhm4+ixKXC
              BTjFlAAlFRkCQdmajOvlD6/uSUA4893u2O+3ql5YK79BYHq5PfTkC2zaDMGGWExX
              QIShVpouZ/zhuAhCtevWS2cPWgJH19ffSfozkLaFTwECgYEA9Tke3SsKLQV2Ap8n
              n89Z3OU9DJYs9L9E80BqjwLpTiUXaxY7syl5gcpjut8vzzrT9+frnU0UnObve8s8
              J9zV9DDDE0YYFceNQXwHn0ZuUG/JPxrUD5WZReKK/SX3g/99TkaZzVTRB8q1oIor
              rzrAujjBQElEyHu0ZJKBbovtKM0CgYEAysV/oIPlam2osSDYboPpMsKg+zcwmPq7
              8CCg/KGFXBPdU+BkWD0TtU3rRfJEE3Mgnu9w31fHLajenNb2v5Bw/8CElILCPym6
              VnyaAMIdwaFCtPkZsyLZRnHXMER93wvjoEH2k1wPKxak6y+7oQKEwIzru5T8SdvE
              Ii6C2zlJSpECgYA0EA6Hck3UxSYK5HNrMICpr1nIxFGDHOCsrG5zMnEKEEHqkGvY
              W+PaNHf8AsqJurmqFmklmmnX7gfGRp3c8LvT/k5MV0NhzF4nGwgbPr7JARK+/Rks
              vdwuxCwyFs94DNQzvDWHLIy8lML+9JbVuymT39zXozahQfJIr/oe2EJfuQKBgQDK
              Wccgbx9tUxuKD+YMe5UnM7UknZHgyC7u1hDxq1qDZct0XbSlneXiA20rczXeVwCR
              uw7fwyAgf6oPyDGbP9CUWRG1hrvD/qdWkae54/1/8qa4JPIxozBCrW56W49lG98/
              WTRxH+h/LmzLyumqJvJFmRvSKT6PkkGrftDVZtiuEQKBgQDytzpAK0/21ohLloJ2
              U+BheMmyA+492DZtAANREC3P5LlGotkCHRIRdYNZ3dPaRWLebDYKnCciCi4rmGI2
              ZwLeiRs3MYFZ90tU8cECiurC+giOGD/IrhstFNjzH00mB9yBB///b+bQ7/738RgG
              meT5O5GY3VuOfj3w01Cck84fyw==
              -----END PRIVATE KEY-----
            cert: |-
              -----BEGIN CERTIFICATE-----
              MIIFGTCCBAGgAwIBAgISA38jxt4SOlL44sEnOx2zXR+/MA0GCSqGSIb3DQEBCwUA
              MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
              EwJSMzAeFw0yMjA1MDYxNDI3MjFaFw0yMjA4MDQxNDI3MjBaMBUxEzARBgNVBAMM
              CiouYW5keWcuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCPEGQ
              XIMlxmGST+ZYgxTv6hHBeNOciXj1glmvSsKxqhTjYmfoi52bTW59szBg8XCUFCul
              kesIdkFzEWaUKMNFinLUIJVlkXMNRbut8deNUzKzGfOO8zj8BUTUg9tecARbyCoK
              JIHqDhpQ4PsKov5Pm9KnVe0Mxh0X7RUR9RZCKSa+vCfK6BCvvu41ghIwTlskufiW
              LI/uptFK5ZQX6h/lb2emhVU5OSrD5wAJd0Qme/Xj8auSLYxKyDnowiihn4z0CtkT
              TPdd+LdYfkQihX/xGUFuSdBx07tgzKWpoKYXe2GhxDFk2dfGM0iXrIyCWJc+mSim
              K5afdIeC+iUWlF4dAgMBAAGjggJEMIICQDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0l
              BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYE
              FFbHE1ywtqQYANiBo/3A8aYHjfkyMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYf
              r52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8u
              bGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMBUG
              A1UdEQQOMAyCCiouYW5keWcuaW8wTAYDVR0gBEUwQzAIBgZngQwBAgEwNwYLKwYB
              BAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5v
              cmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQBByMqx3yJGShDGoToJQodeTjGL
              GwPr60vHaPCQYpYG9gAAAYCZ+4yfAAAEAwBGMEQCIFeYgAwgh0RJh675ml6ODCXh
              Cxcfgm30Fvtb82GbRKtDAiBwaJn79AmEvzd5Pl+RqaoZcUKBc6icnlfMJJg3LPv3
              DwB2ACl5vvCeOTkh8FZzn2Old+W+V32cYAr4+U1dJlwlXceEAAABgJn7jHgAAAQD
              AEcwRQIhANZovABQybDkpXJfQ4zHaVc+dBBzHZsdU2gDs1PoIxAnAiA3nQfJ2erp
              yAVEGPtePPkWOD7GraQvxSYRvH0FfedefzANBgkqhkiG9w0BAQsFAAOCAQEAI2mo
              sVbLrDjuRgP0IyuR5HakuGO74J8NhZmPNAo5BUE6B9huBAMbNpx7KIpJhlFVGiwR
              bnKvWm2g8eR2Hnh8YX6zS0XS1sYf9lx4MOkbF17c1iM2lIeTli6gdW10MiXS+yyF
              caoM6v+PvlELHk0MjTkDOsikeRBwyHtC2UMusVTRYygik6n1g2ICS3R8CeeHP0qd
              wQuFHXNqUdHPhSTI+usE4LCGAD6WrtFC7NB2bjEXFoBaFVKnah52YZ/vlkBhxjci
              VOPnGf0Cjq92P/V5Ojgju3nH3K/RlUKYQNd53nUO8o6E+rOuXKCTBi8rTpOLvoWy
              a7PmHczcAPMfsV63QA==
              -----END CERTIFICATE-----
              -----BEGIN CERTIFICATE-----
              MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
              TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
              cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
              WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
              RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
              AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
              R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
              sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
              NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
              Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
              /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
              AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
              Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
              FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
              AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
              Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
              gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
              PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
              ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
              CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
              lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
              avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
              yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
              yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
              hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
              HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
              MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
              nLRbwHOoq7hHwg==
              -----END CERTIFICATE-----
              -----BEGIN CERTIFICATE-----
              MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
              MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
              DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
              TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
              cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
              AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
              ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
              wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
              LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
              4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
              bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
              sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
              Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
              FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
              SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
              PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
              TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
              SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
              c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
              +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
              ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
              b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
              U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
              MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
              5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
              9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
              WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
              he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
              Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
              -----END CERTIFICATE-----
